<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Seed the countries table with the full list of world countries,
     * including ISO country code, phone country code, currency code,
     * and nationality (demonym) in English and Arabic.
     *
     * Country flags are not stored here - they are served from
     * public/flags/{country_code}.svg, keyed off the country_code below.
     */
    public function run(): void
    {
        $countries = [
            ["en_name" => "Afghanistan", "ar_name" => "أفغانستان", "country_code" => "AF", "phone_code" => "93", "currency_code" => "AFN", "nationality_en" => "Afghan", "nationality_ar" => "أفغاني", "order" => 0],
            ["en_name" => "Albania", "ar_name" => "ألبانيا", "country_code" => "AL", "phone_code" => "355", "currency_code" => "ALL", "nationality_en" => "Albanian", "nationality_ar" => "ألباني", "order" => 1],
            ["en_name" => "Algeria", "ar_name" => "الجزائر", "country_code" => "DZ", "phone_code" => "213", "currency_code" => "DZD", "nationality_en" => "Algerian", "nationality_ar" => "جزائري", "order" => 2],
            ["en_name" => "Andorra", "ar_name" => "أندورا", "country_code" => "AD", "phone_code" => "376", "currency_code" => "EUR", "nationality_en" => "Andorran", "nationality_ar" => "أندوري", "order" => 3],
            ["en_name" => "Angola", "ar_name" => "أنغولا", "country_code" => "AO", "phone_code" => "244", "currency_code" => "AOA", "nationality_en" => "Angolan", "nationality_ar" => "أنغولي", "order" => 4],
            ["en_name" => "Antigua and Barbuda", "ar_name" => "أنتيغوا وباربودا", "country_code" => "AG", "phone_code" => "1268", "currency_code" => "XCD", "nationality_en" => "Antiguan, Barbudan", "nationality_ar" => "أنتيغوي وباربودي", "order" => 5],
            ["en_name" => "Argentina", "ar_name" => "الأرجنتين", "country_code" => "AR", "phone_code" => "54", "currency_code" => "ARS", "nationality_en" => "Argentine", "nationality_ar" => "أرجنتيني", "order" => 6],
            ["en_name" => "Armenia", "ar_name" => "أرمينيا", "country_code" => "AM", "phone_code" => "374", "currency_code" => "AMD", "nationality_en" => "Armenian", "nationality_ar" => "أرمني", "order" => 7],
            ["en_name" => "Australia", "ar_name" => "أستراليا", "country_code" => "AU", "phone_code" => "61", "currency_code" => "AUD", "nationality_en" => "Australian", "nationality_ar" => "أسترالي", "order" => 8],
            ["en_name" => "Austria", "ar_name" => "النمسا", "country_code" => "AT", "phone_code" => "43", "currency_code" => "EUR", "nationality_en" => "Austrian", "nationality_ar" => "نمساوي", "order" => 9],
            ["en_name" => "Azerbaijan", "ar_name" => "أذربيجان", "country_code" => "AZ", "phone_code" => "994", "currency_code" => "AZN", "nationality_en" => "Azerbaijani", "nationality_ar" => "أذربيجاني", "order" => 10],
            ["en_name" => "Bahamas", "ar_name" => "البهاما", "country_code" => "BS", "phone_code" => "1242", "currency_code" => "BSD", "nationality_en" => "Bahamian", "nationality_ar" => "بهامي", "order" => 11],
            ["en_name" => "Bahrain", "ar_name" => "البحرين", "country_code" => "BH", "phone_code" => "973", "currency_code" => "BHD", "nationality_en" => "Bahraini", "nationality_ar" => "بحريني", "order" => 12],
            ["en_name" => "Bangladesh", "ar_name" => "بنغلاديش", "country_code" => "BD", "phone_code" => "880", "currency_code" => "BDT", "nationality_en" => "Bangladeshi", "nationality_ar" => "بنغلاديشي", "order" => 13],
            ["en_name" => "Barbados", "ar_name" => "باربادوس", "country_code" => "BB", "phone_code" => "1246", "currency_code" => "BBD", "nationality_en" => "Barbadian", "nationality_ar" => "باربادوسي", "order" => 14],
            ["en_name" => "Belarus", "ar_name" => "بيلاروسيا", "country_code" => "BY", "phone_code" => "375", "currency_code" => "BYN", "nationality_en" => "Belarusian", "nationality_ar" => "بيلاروسي", "order" => 15],
            ["en_name" => "Belgium", "ar_name" => "بلجيكا", "country_code" => "BE", "phone_code" => "32", "currency_code" => "EUR", "nationality_en" => "Belgian", "nationality_ar" => "بلجيكي", "order" => 16],
            ["en_name" => "Belize", "ar_name" => "بليز", "country_code" => "BZ", "phone_code" => "501", "currency_code" => "BZD", "nationality_en" => "Belizean", "nationality_ar" => "بليزي", "order" => 17],
            ["en_name" => "Benin", "ar_name" => "بنين", "country_code" => "BJ", "phone_code" => "229", "currency_code" => "XOF", "nationality_en" => "Beninese", "nationality_ar" => "بنيني", "order" => 18],
            ["en_name" => "Bhutan", "ar_name" => "بوتان", "country_code" => "BT", "phone_code" => "975", "currency_code" => "BTN", "nationality_en" => "Bhutanese", "nationality_ar" => "بوتاني", "order" => 19],
            ["en_name" => "Bolivia", "ar_name" => "بوليفيا", "country_code" => "BO", "phone_code" => "591", "currency_code" => "BOB", "nationality_en" => "Bolivian", "nationality_ar" => "بوليفي", "order" => 20],
            ["en_name" => "Bosnia and Herzegovina", "ar_name" => "البوسنة والهرسك", "country_code" => "BA", "phone_code" => "387", "currency_code" => "BAM", "nationality_en" => "Bosnian, Herzegovinian", "nationality_ar" => "بوسني", "order" => 21],
            ["en_name" => "Botswana", "ar_name" => "بوتسوانا", "country_code" => "BW", "phone_code" => "267", "currency_code" => "BWP", "nationality_en" => "Motswana", "nationality_ar" => "بوتسواني", "order" => 22],
            ["en_name" => "Brazil", "ar_name" => "البرازيل", "country_code" => "BR", "phone_code" => "55", "currency_code" => "BRL", "nationality_en" => "Brazilian", "nationality_ar" => "برازيلي", "order" => 23],
            ["en_name" => "Brunei", "ar_name" => "بروناي", "country_code" => "BN", "phone_code" => "673", "currency_code" => "BND", "nationality_en" => "Bruneian", "nationality_ar" => "بروناوي", "order" => 24],
            ["en_name" => "Bulgaria", "ar_name" => "بلغاريا", "country_code" => "BG", "phone_code" => "359", "currency_code" => "BGN", "nationality_en" => "Bulgarian", "nationality_ar" => "بلغاري", "order" => 25],
            ["en_name" => "Burkina Faso", "ar_name" => "بوركينا فاسو", "country_code" => "BF", "phone_code" => "226", "currency_code" => "XOF", "nationality_en" => "Burkinabe", "nationality_ar" => "بوركينابي", "order" => 26],
            ["en_name" => "Burundi", "ar_name" => "بوروندي", "country_code" => "BI", "phone_code" => "257", "currency_code" => "BIF", "nationality_en" => "Burundian", "nationality_ar" => "بوروندي", "order" => 27],
            ["en_name" => "Cambodia", "ar_name" => "كمبوديا", "country_code" => "KH", "phone_code" => "855", "currency_code" => "KHR", "nationality_en" => "Cambodian", "nationality_ar" => "كمبودي", "order" => 28],
            ["en_name" => "Cameroon", "ar_name" => "الكاميرون", "country_code" => "CM", "phone_code" => "237", "currency_code" => "XAF", "nationality_en" => "Cameroonian", "nationality_ar" => "كاميروني", "order" => 29],
            ["en_name" => "Canada", "ar_name" => "كندا", "country_code" => "CA", "phone_code" => "1", "currency_code" => "CAD", "nationality_en" => "Canadian", "nationality_ar" => "كندي", "order" => 30],
            ["en_name" => "Cape Verde", "ar_name" => "كابو فيردي", "country_code" => "CV", "phone_code" => "238", "currency_code" => "CVE", "nationality_en" => "Cape Verdian", "nationality_ar" => "رأس أخضري", "order" => 31],
            ["en_name" => "Central African Republic", "ar_name" => "جمهورية أفريقيا الوسطى", "country_code" => "CF", "phone_code" => "236", "currency_code" => "XAF", "nationality_en" => "Central African", "nationality_ar" => "من أفريقيا الوسطى", "order" => 32],
            ["en_name" => "Chad", "ar_name" => "تشاد", "country_code" => "TD", "phone_code" => "235", "currency_code" => "XAF", "nationality_en" => "Chadian", "nationality_ar" => "تشادي", "order" => 33],
            ["en_name" => "Chile", "ar_name" => "تشيلي", "country_code" => "CL", "phone_code" => "56", "currency_code" => "CLP", "nationality_en" => "Chilean", "nationality_ar" => "تشيلي", "order" => 34],
            ["en_name" => "China", "ar_name" => "الصين", "country_code" => "CN", "phone_code" => "86", "currency_code" => "CNY", "nationality_en" => "Chinese", "nationality_ar" => "صيني", "order" => 35],
            ["en_name" => "Colombia", "ar_name" => "كولومبيا", "country_code" => "CO", "phone_code" => "57", "currency_code" => "COP", "nationality_en" => "Colombian", "nationality_ar" => "كولومبي", "order" => 36],
            ["en_name" => "Comoros", "ar_name" => "جزر القمر", "country_code" => "KM", "phone_code" => "269", "currency_code" => "KMF", "nationality_en" => "Comoran", "nationality_ar" => "قمري", "order" => 37],
            ["en_name" => "Costa Rica", "ar_name" => "كوستاريكا", "country_code" => "CR", "phone_code" => "506", "currency_code" => "CRC", "nationality_en" => "Costa Rican", "nationality_ar" => "كوستاريكي", "order" => 38],
            ["en_name" => "Croatia", "ar_name" => "كرواتيا", "country_code" => "HR", "phone_code" => "385", "currency_code" => "EUR", "nationality_en" => "Croatian", "nationality_ar" => "كرواتي", "order" => 39],
            ["en_name" => "Cuba", "ar_name" => "كوبا", "country_code" => "CU", "phone_code" => "53", "currency_code" => "CUC", "nationality_en" => "Cuban", "nationality_ar" => "كوبي", "order" => 40],
            ["en_name" => "Cyprus", "ar_name" => "قبرص", "country_code" => "CY", "phone_code" => "357", "currency_code" => "EUR", "nationality_en" => "Cypriot", "nationality_ar" => "قبرصي", "order" => 41],
            ["en_name" => "Czechia", "ar_name" => "التشيك", "country_code" => "CZ", "phone_code" => "420", "currency_code" => "CZK", "nationality_en" => "Czech", "nationality_ar" => "تشيكي", "order" => 42],
            ["en_name" => "DR Congo", "ar_name" => "جمهورية الكونغو الديمقراطية", "country_code" => "CD", "phone_code" => "243", "currency_code" => "CDF", "nationality_en" => "Congolese", "nationality_ar" => "كونغولي", "order" => 43],
            ["en_name" => "Denmark", "ar_name" => "الدنمارك", "country_code" => "DK", "phone_code" => "45", "currency_code" => "DKK", "nationality_en" => "Danish", "nationality_ar" => "دنماركي", "order" => 44],
            ["en_name" => "Djibouti", "ar_name" => "جيبوتي", "country_code" => "DJ", "phone_code" => "253", "currency_code" => "DJF", "nationality_en" => "Djibouti", "nationality_ar" => "جيبوتي", "order" => 45],
            ["en_name" => "Dominica", "ar_name" => "دومينيكا", "country_code" => "DM", "phone_code" => "1767", "currency_code" => "XCD", "nationality_en" => "Dominican", "nationality_ar" => "دومينيكي", "order" => 46],
            ["en_name" => "Dominican Republic", "ar_name" => "جمهورية الدومينيكان", "country_code" => "DO", "phone_code" => "1", "currency_code" => "DOP", "nationality_en" => "Dominican", "nationality_ar" => "دومينيكاني", "order" => 47],
            ["en_name" => "Ecuador", "ar_name" => "الإكوادور", "country_code" => "EC", "phone_code" => "593", "currency_code" => "USD", "nationality_en" => "Ecuadorean", "nationality_ar" => "إكوادوري", "order" => 48],
            ["en_name" => "Egypt", "ar_name" => "مصر", "country_code" => "EG", "phone_code" => "20", "currency_code" => "EGP", "nationality_en" => "Egyptian", "nationality_ar" => "مصري", "order" => 49],
            ["en_name" => "El Salvador", "ar_name" => "السلفادور", "country_code" => "SV", "phone_code" => "503", "currency_code" => "USD", "nationality_en" => "Salvadoran", "nationality_ar" => "سلفادوري", "order" => 50],
            ["en_name" => "Equatorial Guinea", "ar_name" => "غينيا الاستوائية", "country_code" => "GQ", "phone_code" => "240", "currency_code" => "XAF", "nationality_en" => "Equatorial Guinean", "nationality_ar" => "غيني استوائي", "order" => 51],
            ["en_name" => "Eritrea", "ar_name" => "إريتريا", "country_code" => "ER", "phone_code" => "291", "currency_code" => "ERN", "nationality_en" => "Eritrean", "nationality_ar" => "إريتري", "order" => 52],
            ["en_name" => "Estonia", "ar_name" => "إستونيا", "country_code" => "EE", "phone_code" => "372", "currency_code" => "EUR", "nationality_en" => "Estonian", "nationality_ar" => "إستوني", "order" => 53],
            ["en_name" => "Eswatini", "ar_name" => "إسواتيني", "country_code" => "SZ", "phone_code" => "268", "currency_code" => "SZL", "nationality_en" => "Swazi", "nationality_ar" => "إسواتيني", "order" => 54],
            ["en_name" => "Ethiopia", "ar_name" => "إثيوبيا", "country_code" => "ET", "phone_code" => "251", "currency_code" => "ETB", "nationality_en" => "Ethiopian", "nationality_ar" => "إثيوبي", "order" => 55],
            ["en_name" => "Fiji", "ar_name" => "فيجي", "country_code" => "FJ", "phone_code" => "679", "currency_code" => "FJD", "nationality_en" => "Fijian", "nationality_ar" => "فيجي", "order" => 56],
            ["en_name" => "Finland", "ar_name" => "فنلندا", "country_code" => "FI", "phone_code" => "358", "currency_code" => "EUR", "nationality_en" => "Finnish", "nationality_ar" => "فنلندي", "order" => 57],
            ["en_name" => "France", "ar_name" => "فرنسا", "country_code" => "FR", "phone_code" => "33", "currency_code" => "EUR", "nationality_en" => "French", "nationality_ar" => "فرنسي", "order" => 58],
            ["en_name" => "Gabon", "ar_name" => "الغابون", "country_code" => "GA", "phone_code" => "241", "currency_code" => "XAF", "nationality_en" => "Gabonese", "nationality_ar" => "غابوني", "order" => 59],
            ["en_name" => "Gambia", "ar_name" => "غامبيا", "country_code" => "GM", "phone_code" => "220", "currency_code" => "GMD", "nationality_en" => "Gambian", "nationality_ar" => "غامبي", "order" => 60],
            ["en_name" => "Georgia", "ar_name" => "جورجيا", "country_code" => "GE", "phone_code" => "995", "currency_code" => "GEL", "nationality_en" => "Georgian", "nationality_ar" => "جورجي", "order" => 61],
            ["en_name" => "Germany", "ar_name" => "ألمانيا", "country_code" => "DE", "phone_code" => "49", "currency_code" => "EUR", "nationality_en" => "German", "nationality_ar" => "ألماني", "order" => 62],
            ["en_name" => "Ghana", "ar_name" => "غانا", "country_code" => "GH", "phone_code" => "233", "currency_code" => "GHS", "nationality_en" => "Ghanaian", "nationality_ar" => "غاني", "order" => 63],
            ["en_name" => "Greece", "ar_name" => "اليونان", "country_code" => "GR", "phone_code" => "30", "currency_code" => "EUR", "nationality_en" => "Greek", "nationality_ar" => "يوناني", "order" => 64],
            ["en_name" => "Grenada", "ar_name" => "غرينادا", "country_code" => "GD", "phone_code" => "1473", "currency_code" => "XCD", "nationality_en" => "Grenadian", "nationality_ar" => "غرينادي", "order" => 65],
            ["en_name" => "Guatemala", "ar_name" => "غواتيمالا", "country_code" => "GT", "phone_code" => "502", "currency_code" => "GTQ", "nationality_en" => "Guatemalan", "nationality_ar" => "غواتيمالي", "order" => 66],
            ["en_name" => "Guinea", "ar_name" => "غينيا", "country_code" => "GN", "phone_code" => "224", "currency_code" => "GNF", "nationality_en" => "Guinean", "nationality_ar" => "غيني", "order" => 67],
            ["en_name" => "Guinea-Bissau", "ar_name" => "غينيا بيساو", "country_code" => "GW", "phone_code" => "245", "currency_code" => "XOF", "nationality_en" => "Guinea-Bissauan", "nationality_ar" => "غيني بيساوي", "order" => 68],
            ["en_name" => "Guyana", "ar_name" => "غيانا", "country_code" => "GY", "phone_code" => "592", "currency_code" => "GYD", "nationality_en" => "Guyanese", "nationality_ar" => "غياني", "order" => 69],
            ["en_name" => "Haiti", "ar_name" => "هايتي", "country_code" => "HT", "phone_code" => "509", "currency_code" => "HTG", "nationality_en" => "Haitian", "nationality_ar" => "هايتي", "order" => 70],
            ["en_name" => "Honduras", "ar_name" => "هندوراس", "country_code" => "HN", "phone_code" => "504", "currency_code" => "HNL", "nationality_en" => "Honduran", "nationality_ar" => "هندوراسي", "order" => 71],
            ["en_name" => "Hungary", "ar_name" => "المجر", "country_code" => "HU", "phone_code" => "36", "currency_code" => "HUF", "nationality_en" => "Hungarian", "nationality_ar" => "مجري", "order" => 72],
            ["en_name" => "Iceland", "ar_name" => "آيسلندا", "country_code" => "IS", "phone_code" => "354", "currency_code" => "ISK", "nationality_en" => "Icelander", "nationality_ar" => "آيسلندي", "order" => 73],
            ["en_name" => "India", "ar_name" => "الهند", "country_code" => "IN", "phone_code" => "91", "currency_code" => "INR", "nationality_en" => "Indian", "nationality_ar" => "هندي", "order" => 74],
            ["en_name" => "Indonesia", "ar_name" => "إندونيسيا", "country_code" => "ID", "phone_code" => "62", "currency_code" => "IDR", "nationality_en" => "Indonesian", "nationality_ar" => "إندونيسي", "order" => 75],
            ["en_name" => "Iran", "ar_name" => "إيران", "country_code" => "IR", "phone_code" => "98", "currency_code" => "IRR", "nationality_en" => "Iranian", "nationality_ar" => "إيراني", "order" => 76],
            ["en_name" => "Iraq", "ar_name" => "العراق", "country_code" => "IQ", "phone_code" => "964", "currency_code" => "IQD", "nationality_en" => "Iraqi", "nationality_ar" => "عراقي", "order" => 77],
            ["en_name" => "Ireland", "ar_name" => "أيرلندا", "country_code" => "IE", "phone_code" => "353", "currency_code" => "EUR", "nationality_en" => "Irish", "nationality_ar" => "أيرلندي", "order" => 78],
            ["en_name" => "Israel", "ar_name" => "إسرائيل", "country_code" => "IL", "phone_code" => "972", "currency_code" => "ILS", "nationality_en" => "Israeli", "nationality_ar" => "إسرائيلي", "order" => 79],
            ["en_name" => "Italy", "ar_name" => "إيطاليا", "country_code" => "IT", "phone_code" => "39", "currency_code" => "EUR", "nationality_en" => "Italian", "nationality_ar" => "إيطالي", "order" => 80],
            ["en_name" => "Ivory Coast", "ar_name" => "ساحل العاج", "country_code" => "CI", "phone_code" => "225", "currency_code" => "XOF", "nationality_en" => "Ivorian", "nationality_ar" => "إيفواري", "order" => 81],
            ["en_name" => "Jamaica", "ar_name" => "جامايكا", "country_code" => "JM", "phone_code" => "1876", "currency_code" => "JMD", "nationality_en" => "Jamaican", "nationality_ar" => "جامايكي", "order" => 82],
            ["en_name" => "Japan", "ar_name" => "اليابان", "country_code" => "JP", "phone_code" => "81", "currency_code" => "JPY", "nationality_en" => "Japanese", "nationality_ar" => "ياباني", "order" => 83],
            ["en_name" => "Jordan", "ar_name" => "الأردن", "country_code" => "JO", "phone_code" => "962", "currency_code" => "JOD", "nationality_en" => "Jordanian", "nationality_ar" => "أردني", "order" => 84],
            ["en_name" => "Kazakhstan", "ar_name" => "كازاخستان", "country_code" => "KZ", "phone_code" => "7", "currency_code" => "KZT", "nationality_en" => "Kazakhstani", "nationality_ar" => "كازاخستاني", "order" => 85],
            ["en_name" => "Kenya", "ar_name" => "كينيا", "country_code" => "KE", "phone_code" => "254", "currency_code" => "KES", "nationality_en" => "Kenyan", "nationality_ar" => "كيني", "order" => 86],
            ["en_name" => "Kiribati", "ar_name" => "كيريباتي", "country_code" => "KI", "phone_code" => "686", "currency_code" => "AUD", "nationality_en" => "I-Kiribati", "nationality_ar" => "كيريباتي", "order" => 87],
            ["en_name" => "Kuwait", "ar_name" => "الكويت", "country_code" => "KW", "phone_code" => "965", "currency_code" => "KWD", "nationality_en" => "Kuwaiti", "nationality_ar" => "كويتي", "order" => 88],
            ["en_name" => "Kyrgyzstan", "ar_name" => "قيرغيزستان", "country_code" => "KG", "phone_code" => "996", "currency_code" => "KGS", "nationality_en" => "Kirghiz", "nationality_ar" => "قيرغيزستاني", "order" => 89],
            ["en_name" => "Laos", "ar_name" => "لاوس", "country_code" => "LA", "phone_code" => "856", "currency_code" => "LAK", "nationality_en" => "Laotian", "nationality_ar" => "لاوسي", "order" => 90],
            ["en_name" => "Latvia", "ar_name" => "لاتفيا", "country_code" => "LV", "phone_code" => "371", "currency_code" => "EUR", "nationality_en" => "Latvian", "nationality_ar" => "لاتفي", "order" => 91],
            ["en_name" => "Lebanon", "ar_name" => "لبنان", "country_code" => "LB", "phone_code" => "961", "currency_code" => "LBP", "nationality_en" => "Lebanese", "nationality_ar" => "لبناني", "order" => 92],
            ["en_name" => "Lesotho", "ar_name" => "ليسوتو", "country_code" => "LS", "phone_code" => "266", "currency_code" => "LSL", "nationality_en" => "Mosotho", "nationality_ar" => "ليسوتي", "order" => 93],
            ["en_name" => "Liberia", "ar_name" => "ليبيريا", "country_code" => "LR", "phone_code" => "231", "currency_code" => "LRD", "nationality_en" => "Liberian", "nationality_ar" => "ليبيري", "order" => 94],
            ["en_name" => "Libya", "ar_name" => "ليبيا", "country_code" => "LY", "phone_code" => "218", "currency_code" => "LYD", "nationality_en" => "Libyan", "nationality_ar" => "ليبي", "order" => 95],
            ["en_name" => "Liechtenstein", "ar_name" => "ليختنشتاين", "country_code" => "LI", "phone_code" => "423", "currency_code" => "CHF", "nationality_en" => "Liechtensteiner", "nationality_ar" => "ليختنشتايني", "order" => 96],
            ["en_name" => "Lithuania", "ar_name" => "ليتوانيا", "country_code" => "LT", "phone_code" => "370", "currency_code" => "EUR", "nationality_en" => "Lithuanian", "nationality_ar" => "ليتواني", "order" => 97],
            ["en_name" => "Luxembourg", "ar_name" => "لوكسمبورغ", "country_code" => "LU", "phone_code" => "352", "currency_code" => "EUR", "nationality_en" => "Luxembourger", "nationality_ar" => "لوكسمبورغي", "order" => 98],
            ["en_name" => "Madagascar", "ar_name" => "مدغشقر", "country_code" => "MG", "phone_code" => "261", "currency_code" => "MGA", "nationality_en" => "Malagasy", "nationality_ar" => "مدغشقري", "order" => 99],
            ["en_name" => "Malawi", "ar_name" => "مالاوي", "country_code" => "MW", "phone_code" => "265", "currency_code" => "MWK", "nationality_en" => "Malawian", "nationality_ar" => "ملاوي", "order" => 100],
            ["en_name" => "Malaysia", "ar_name" => "ماليزيا", "country_code" => "MY", "phone_code" => "60", "currency_code" => "MYR", "nationality_en" => "Malaysian", "nationality_ar" => "ماليزي", "order" => 101],
            ["en_name" => "Maldives", "ar_name" => "المالديف", "country_code" => "MV", "phone_code" => "960", "currency_code" => "MVR", "nationality_en" => "Maldivan", "nationality_ar" => "مالديفي", "order" => 102],
            ["en_name" => "Mali", "ar_name" => "مالي", "country_code" => "ML", "phone_code" => "223", "currency_code" => "XOF", "nationality_en" => "Malian", "nationality_ar" => "مالي", "order" => 103],
            ["en_name" => "Malta", "ar_name" => "مالطا", "country_code" => "MT", "phone_code" => "356", "currency_code" => "EUR", "nationality_en" => "Maltese", "nationality_ar" => "مالطي", "order" => 104],
            ["en_name" => "Marshall Islands", "ar_name" => "جزر مارشال", "country_code" => "MH", "phone_code" => "692", "currency_code" => "USD", "nationality_en" => "Marshallese", "nationality_ar" => "مارشالي", "order" => 105],
            ["en_name" => "Mauritania", "ar_name" => "موريتانيا", "country_code" => "MR", "phone_code" => "222", "currency_code" => "MRU", "nationality_en" => "Mauritanian", "nationality_ar" => "موريتاني", "order" => 106],
            ["en_name" => "Mauritius", "ar_name" => "موريشيوس", "country_code" => "MU", "phone_code" => "230", "currency_code" => "MUR", "nationality_en" => "Mauritian", "nationality_ar" => "موريشيوسي", "order" => 107],
            ["en_name" => "Mexico", "ar_name" => "المكسيك", "country_code" => "MX", "phone_code" => "52", "currency_code" => "MXN", "nationality_en" => "Mexican", "nationality_ar" => "مكسيكي", "order" => 108],
            ["en_name" => "Micronesia", "ar_name" => "ميكرونيسيا", "country_code" => "FM", "phone_code" => "691", "currency_code" => "USD", "nationality_en" => "Micronesian", "nationality_ar" => "ميكرونيسي", "order" => 109],
            ["en_name" => "Moldova", "ar_name" => "مولدوفا", "country_code" => "MD", "phone_code" => "373", "currency_code" => "MDL", "nationality_en" => "Moldovan", "nationality_ar" => "مولدوفي", "order" => 110],
            ["en_name" => "Monaco", "ar_name" => "موناكو", "country_code" => "MC", "phone_code" => "377", "currency_code" => "EUR", "nationality_en" => "Monegasque", "nationality_ar" => "موناكي", "order" => 111],
            ["en_name" => "Mongolia", "ar_name" => "منغوليا", "country_code" => "MN", "phone_code" => "976", "currency_code" => "MNT", "nationality_en" => "Mongolian", "nationality_ar" => "منغولي", "order" => 112],
            ["en_name" => "Montenegro", "ar_name" => "الجبل الأسود", "country_code" => "ME", "phone_code" => "382", "currency_code" => "EUR", "nationality_en" => "Montenegrin", "nationality_ar" => "مونتينيغري", "order" => 113],
            ["en_name" => "Morocco", "ar_name" => "المغرب", "country_code" => "MA", "phone_code" => "212", "currency_code" => "MAD", "nationality_en" => "Moroccan", "nationality_ar" => "مغربي", "order" => 114],
            ["en_name" => "Mozambique", "ar_name" => "موزمبيق", "country_code" => "MZ", "phone_code" => "258", "currency_code" => "MZN", "nationality_en" => "Mozambican", "nationality_ar" => "موزمبيقي", "order" => 115],
            ["en_name" => "Myanmar", "ar_name" => "ميانمار", "country_code" => "MM", "phone_code" => "95", "currency_code" => "MMK", "nationality_en" => "Burmese", "nationality_ar" => "ميانماري", "order" => 116],
            ["en_name" => "Namibia", "ar_name" => "ناميبيا", "country_code" => "NA", "phone_code" => "264", "currency_code" => "NAD", "nationality_en" => "Namibian", "nationality_ar" => "ناميبي", "order" => 117],
            ["en_name" => "Nauru", "ar_name" => "ناورو", "country_code" => "NR", "phone_code" => "674", "currency_code" => "AUD", "nationality_en" => "Nauruan", "nationality_ar" => "ناوروي", "order" => 118],
            ["en_name" => "Nepal", "ar_name" => "نيبال", "country_code" => "NP", "phone_code" => "977", "currency_code" => "NPR", "nationality_en" => "Nepalese", "nationality_ar" => "نيبالي", "order" => 119],
            ["en_name" => "Netherlands", "ar_name" => "هولندا", "country_code" => "NL", "phone_code" => "31", "currency_code" => "EUR", "nationality_en" => "Dutch", "nationality_ar" => "هولندي", "order" => 120],
            ["en_name" => "New Zealand", "ar_name" => "نيوزيلندا", "country_code" => "NZ", "phone_code" => "64", "currency_code" => "NZD", "nationality_en" => "New Zealander", "nationality_ar" => "نيوزيلندي", "order" => 121],
            ["en_name" => "Nicaragua", "ar_name" => "نيكاراغوا", "country_code" => "NI", "phone_code" => "505", "currency_code" => "NIO", "nationality_en" => "Nicaraguan", "nationality_ar" => "نيكاراغوي", "order" => 122],
            ["en_name" => "Niger", "ar_name" => "النيجر", "country_code" => "NE", "phone_code" => "227", "currency_code" => "XOF", "nationality_en" => "Nigerien", "nationality_ar" => "نيجري", "order" => 123],
            ["en_name" => "Nigeria", "ar_name" => "نيجيريا", "country_code" => "NG", "phone_code" => "234", "currency_code" => "NGN", "nationality_en" => "Nigerian", "nationality_ar" => "نيجيري", "order" => 124],
            ["en_name" => "North Korea", "ar_name" => "كوريا الشمالية", "country_code" => "KP", "phone_code" => "850", "currency_code" => "KPW", "nationality_en" => "North Korean", "nationality_ar" => "كوري شمالي", "order" => 125],
            ["en_name" => "North Macedonia", "ar_name" => "شمال مقدونيا", "country_code" => "MK", "phone_code" => "389", "currency_code" => "MKD", "nationality_en" => "Macedonian", "nationality_ar" => "مقدوني", "order" => 126],
            ["en_name" => "Norway", "ar_name" => "النرويج", "country_code" => "NO", "phone_code" => "47", "currency_code" => "NOK", "nationality_en" => "Norwegian", "nationality_ar" => "نرويجي", "order" => 127],
            ["en_name" => "Oman", "ar_name" => "سلطنة عمان", "country_code" => "OM", "phone_code" => "968", "currency_code" => "OMR", "nationality_en" => "Omani", "nationality_ar" => "عماني", "order" => 128],
            ["en_name" => "Pakistan", "ar_name" => "باكستان", "country_code" => "PK", "phone_code" => "92", "currency_code" => "PKR", "nationality_en" => "Pakistani", "nationality_ar" => "باكستاني", "order" => 129],
            ["en_name" => "Palau", "ar_name" => "بالاو", "country_code" => "PW", "phone_code" => "680", "currency_code" => "USD", "nationality_en" => "Palauan", "nationality_ar" => "بالاوي", "order" => 130],
            ["en_name" => "Palestine", "ar_name" => "فلسطين", "country_code" => "PS", "phone_code" => "970", "currency_code" => "EGP", "nationality_en" => "Palestinian", "nationality_ar" => "فلسطيني", "order" => 131],
            ["en_name" => "Panama", "ar_name" => "بنما", "country_code" => "PA", "phone_code" => "507", "currency_code" => "PAB", "nationality_en" => "Panamanian", "nationality_ar" => "بنمي", "order" => 132],
            ["en_name" => "Papua New Guinea", "ar_name" => "بابوا غينيا الجديدة", "country_code" => "PG", "phone_code" => "675", "currency_code" => "PGK", "nationality_en" => "Papua New Guinean", "nationality_ar" => "من بابوا غينيا الجديدة", "order" => 133],
            ["en_name" => "Paraguay", "ar_name" => "باراغواي", "country_code" => "PY", "phone_code" => "595", "currency_code" => "PYG", "nationality_en" => "Paraguayan", "nationality_ar" => "باراغواي", "order" => 134],
            ["en_name" => "Peru", "ar_name" => "بيرو", "country_code" => "PE", "phone_code" => "51", "currency_code" => "PEN", "nationality_en" => "Peruvian", "nationality_ar" => "بيروفي", "order" => 135],
            ["en_name" => "Philippines", "ar_name" => "الفلبين", "country_code" => "PH", "phone_code" => "63", "currency_code" => "PHP", "nationality_en" => "Filipino", "nationality_ar" => "فلبيني", "order" => 136],
            ["en_name" => "Poland", "ar_name" => "بولندا", "country_code" => "PL", "phone_code" => "48", "currency_code" => "PLN", "nationality_en" => "Polish", "nationality_ar" => "بولندي", "order" => 137],
            ["en_name" => "Portugal", "ar_name" => "البرتغال", "country_code" => "PT", "phone_code" => "351", "currency_code" => "EUR", "nationality_en" => "Portuguese", "nationality_ar" => "برتغالي", "order" => 138],
            ["en_name" => "Qatar", "ar_name" => "قطر", "country_code" => "QA", "phone_code" => "974", "currency_code" => "QAR", "nationality_en" => "Qatari", "nationality_ar" => "قطري", "order" => 139],
            ["en_name" => "Republic of the Congo", "ar_name" => "جمهورية الكونغو", "country_code" => "CG", "phone_code" => "242", "currency_code" => "XAF", "nationality_en" => "Congolese", "nationality_ar" => "كونغولي", "order" => 140],
            ["en_name" => "Romania", "ar_name" => "رومانيا", "country_code" => "RO", "phone_code" => "40", "currency_code" => "RON", "nationality_en" => "Romanian", "nationality_ar" => "روماني", "order" => 141],
            ["en_name" => "Russia", "ar_name" => "روسيا", "country_code" => "RU", "phone_code" => "7", "currency_code" => "RUB", "nationality_en" => "Russian", "nationality_ar" => "روسي", "order" => 142],
            ["en_name" => "Rwanda", "ar_name" => "رواندا", "country_code" => "RW", "phone_code" => "250", "currency_code" => "RWF", "nationality_en" => "Rwandan", "nationality_ar" => "رواندي", "order" => 143],
            ["en_name" => "Saint Kitts and Nevis", "ar_name" => "سانت كيتس ونيفيس", "country_code" => "KN", "phone_code" => "1869", "currency_code" => "XCD", "nationality_en" => "Kittitian or Nevisian", "nationality_ar" => "من سانت كيتس ونيفيس", "order" => 144],
            ["en_name" => "Saint Lucia", "ar_name" => "سانت لوسيا", "country_code" => "LC", "phone_code" => "1758", "currency_code" => "XCD", "nationality_en" => "Saint Lucian", "nationality_ar" => "سانت لوسي", "order" => 145],
            ["en_name" => "Saint Vincent and the Grenadines", "ar_name" => "سانت فينسنت والغرينادين", "country_code" => "VC", "phone_code" => "1784", "currency_code" => "XCD", "nationality_en" => "Saint Vincentian", "nationality_ar" => "من سانت فينسنت والغرينادين", "order" => 146],
            ["en_name" => "Samoa", "ar_name" => "ساموا", "country_code" => "WS", "phone_code" => "685", "currency_code" => "WST", "nationality_en" => "Samoan", "nationality_ar" => "ساموي", "order" => 147],
            ["en_name" => "San Marino", "ar_name" => "سان مارينو", "country_code" => "SM", "phone_code" => "378", "currency_code" => "EUR", "nationality_en" => "Sammarinese", "nationality_ar" => "سان ماريني", "order" => 148],
            ["en_name" => "Saudi Arabia", "ar_name" => "السعودية", "country_code" => "SA", "phone_code" => "966", "currency_code" => "SAR", "nationality_en" => "Saudi Arabian", "nationality_ar" => "سعودي", "order" => 149],
            ["en_name" => "Senegal", "ar_name" => "السنغال", "country_code" => "SN", "phone_code" => "221", "currency_code" => "XOF", "nationality_en" => "Senegalese", "nationality_ar" => "سنغالي", "order" => 150],
            ["en_name" => "Serbia", "ar_name" => "صربيا", "country_code" => "RS", "phone_code" => "381", "currency_code" => "RSD", "nationality_en" => "Serbian", "nationality_ar" => "صربي", "order" => 151],
            ["en_name" => "Seychelles", "ar_name" => "سيشل", "country_code" => "SC", "phone_code" => "248", "currency_code" => "SCR", "nationality_en" => "Seychellois", "nationality_ar" => "سيشلي", "order" => 152],
            ["en_name" => "Sierra Leone", "ar_name" => "سيراليون", "country_code" => "SL", "phone_code" => "232", "currency_code" => "SLL", "nationality_en" => "Sierra Leonean", "nationality_ar" => "سيراليوني", "order" => 153],
            ["en_name" => "Singapore", "ar_name" => "سنغافورة", "country_code" => "SG", "phone_code" => "65", "currency_code" => "SGD", "nationality_en" => "Singaporean", "nationality_ar" => "سنغافوري", "order" => 154],
            ["en_name" => "Slovakia", "ar_name" => "سلوفاكيا", "country_code" => "SK", "phone_code" => "421", "currency_code" => "EUR", "nationality_en" => "Slovak", "nationality_ar" => "سلوفاكي", "order" => 155],
            ["en_name" => "Slovenia", "ar_name" => "سلوفينيا", "country_code" => "SI", "phone_code" => "386", "currency_code" => "EUR", "nationality_en" => "Slovene", "nationality_ar" => "سلوفيني", "order" => 156],
            ["en_name" => "Solomon Islands", "ar_name" => "جزر سليمان", "country_code" => "SB", "phone_code" => "677", "currency_code" => "SBD", "nationality_en" => "Solomon Islander", "nationality_ar" => "من جزر سليمان", "order" => 157],
            ["en_name" => "Somalia", "ar_name" => "الصومال", "country_code" => "SO", "phone_code" => "252", "currency_code" => "SOS", "nationality_en" => "Somali", "nationality_ar" => "صومالي", "order" => 158],
            ["en_name" => "South Africa", "ar_name" => "جنوب أفريقيا", "country_code" => "ZA", "phone_code" => "27", "currency_code" => "ZAR", "nationality_en" => "South African", "nationality_ar" => "جنوب أفريقي", "order" => 159],
            ["en_name" => "South Korea", "ar_name" => "كوريا الجنوبية", "country_code" => "KR", "phone_code" => "82", "currency_code" => "KRW", "nationality_en" => "South Korean", "nationality_ar" => "كوري جنوبي", "order" => 160],
            ["en_name" => "South Sudan", "ar_name" => "جنوب السودان", "country_code" => "SS", "phone_code" => "211", "currency_code" => "SSP", "nationality_en" => "South Sudanese", "nationality_ar" => "جنوب سوداني", "order" => 161],
            ["en_name" => "Spain", "ar_name" => "إسبانيا", "country_code" => "ES", "phone_code" => "34", "currency_code" => "EUR", "nationality_en" => "Spanish", "nationality_ar" => "إسباني", "order" => 162],
            ["en_name" => "Sri Lanka", "ar_name" => "سريلانكا", "country_code" => "LK", "phone_code" => "94", "currency_code" => "LKR", "nationality_en" => "Sri Lankan", "nationality_ar" => "سريلانكي", "order" => 163],
            ["en_name" => "Sudan", "ar_name" => "السودان", "country_code" => "SD", "phone_code" => "249", "currency_code" => "SDG", "nationality_en" => "Sudanese", "nationality_ar" => "سوداني", "order" => 164],
            ["en_name" => "Suriname", "ar_name" => "سورينام", "country_code" => "SR", "phone_code" => "597", "currency_code" => "SRD", "nationality_en" => "Surinamer", "nationality_ar" => "سورينامي", "order" => 165],
            ["en_name" => "Sweden", "ar_name" => "السويد", "country_code" => "SE", "phone_code" => "46", "currency_code" => "SEK", "nationality_en" => "Swedish", "nationality_ar" => "سويدي", "order" => 166],
            ["en_name" => "Switzerland", "ar_name" => "سويسرا", "country_code" => "CH", "phone_code" => "41", "currency_code" => "CHF", "nationality_en" => "Swiss", "nationality_ar" => "سويسري", "order" => 167],
            ["en_name" => "Syria", "ar_name" => "سوريا", "country_code" => "SY", "phone_code" => "963", "currency_code" => "SYP", "nationality_en" => "Syrian", "nationality_ar" => "سوري", "order" => 168],
            ["en_name" => "São Tomé and Príncipe", "ar_name" => "ساو تومي وبرينسيب", "country_code" => "ST", "phone_code" => "239", "currency_code" => "STN", "nationality_en" => "Sao Tomean", "nationality_ar" => "من ساو تومي وبرينسيب", "order" => 169],
            ["en_name" => "Taiwan", "ar_name" => "تايوان", "country_code" => "TW", "phone_code" => "886", "currency_code" => "TWD", "nationality_en" => "Taiwanese", "nationality_ar" => "تايواني", "order" => 170],
            ["en_name" => "Tajikistan", "ar_name" => "طاجيكستان", "country_code" => "TJ", "phone_code" => "992", "currency_code" => "TJS", "nationality_en" => "Tadzhik", "nationality_ar" => "طاجيكستاني", "order" => 171],
            ["en_name" => "Tanzania", "ar_name" => "تنزانيا", "country_code" => "TZ", "phone_code" => "255", "currency_code" => "TZS", "nationality_en" => "Tanzanian", "nationality_ar" => "تنزاني", "order" => 172],
            ["en_name" => "Thailand", "ar_name" => "تايلند", "country_code" => "TH", "phone_code" => "66", "currency_code" => "THB", "nationality_en" => "Thai", "nationality_ar" => "تايلاندي", "order" => 173],
            ["en_name" => "Timor-Leste", "ar_name" => "تيمور الشرقية", "country_code" => "TL", "phone_code" => "670", "currency_code" => "USD", "nationality_en" => "East Timorese", "nationality_ar" => "تيموري", "order" => 174],
            ["en_name" => "Togo", "ar_name" => "توغو", "country_code" => "TG", "phone_code" => "228", "currency_code" => "XOF", "nationality_en" => "Togolese", "nationality_ar" => "توغولي", "order" => 175],
            ["en_name" => "Tonga", "ar_name" => "تونغا", "country_code" => "TO", "phone_code" => "676", "currency_code" => "TOP", "nationality_en" => "Tongan", "nationality_ar" => "تونغي", "order" => 176],
            ["en_name" => "Trinidad and Tobago", "ar_name" => "ترينيداد وتوباغو", "country_code" => "TT", "phone_code" => "1868", "currency_code" => "TTD", "nationality_en" => "Trinidadian", "nationality_ar" => "ترينيدادي وتوباغوي", "order" => 177],
            ["en_name" => "Tunisia", "ar_name" => "تونس", "country_code" => "TN", "phone_code" => "216", "currency_code" => "TND", "nationality_en" => "Tunisian", "nationality_ar" => "تونسي", "order" => 178],
            ["en_name" => "Turkmenistan", "ar_name" => "تركمانستان", "country_code" => "TM", "phone_code" => "993", "currency_code" => "TMT", "nationality_en" => "Turkmen", "nationality_ar" => "تركمانستاني", "order" => 179],
            ["en_name" => "Tuvalu", "ar_name" => "توفالو", "country_code" => "TV", "phone_code" => "688", "currency_code" => "AUD", "nationality_en" => "Tuvaluan", "nationality_ar" => "توفالي", "order" => 180],
            ["en_name" => "Türkiye", "ar_name" => "تركيا", "country_code" => "TR", "phone_code" => "90", "currency_code" => "TRY", "nationality_en" => "Turkish", "nationality_ar" => "تركي", "order" => 181],
            ["en_name" => "Uganda", "ar_name" => "أوغندا", "country_code" => "UG", "phone_code" => "256", "currency_code" => "UGX", "nationality_en" => "Ugandan", "nationality_ar" => "أوغندي", "order" => 182],
            ["en_name" => "Ukraine", "ar_name" => "أوكرانيا", "country_code" => "UA", "phone_code" => "380", "currency_code" => "UAH", "nationality_en" => "Ukrainian", "nationality_ar" => "أوكراني", "order" => 183],
            ["en_name" => "United Arab Emirates", "ar_name" => "الإمارات", "country_code" => "AE", "phone_code" => "971", "currency_code" => "AED", "nationality_en" => "Emirati", "nationality_ar" => "إماراتي", "order" => 184],
            ["en_name" => "United Kingdom", "ar_name" => "المملكة المتحدة", "country_code" => "GB", "phone_code" => "44", "currency_code" => "GBP", "nationality_en" => "British", "nationality_ar" => "بريطاني", "order" => 185],
            ["en_name" => "United States", "ar_name" => "الولايات المتحدة", "country_code" => "US", "phone_code" => "1", "currency_code" => "USD", "nationality_en" => "American", "nationality_ar" => "أمريكي", "order" => 186],
            ["en_name" => "Uruguay", "ar_name" => "الأوروغواي", "country_code" => "UY", "phone_code" => "598", "currency_code" => "UYU", "nationality_en" => "Uruguayan", "nationality_ar" => "أوروغواياني", "order" => 187],
            ["en_name" => "Uzbekistan", "ar_name" => "أوزبكستان", "country_code" => "UZ", "phone_code" => "998", "currency_code" => "UZS", "nationality_en" => "Uzbekistani", "nationality_ar" => "أوزبكستاني", "order" => 188],
            ["en_name" => "Vanuatu", "ar_name" => "فانواتو", "country_code" => "VU", "phone_code" => "678", "currency_code" => "VUV", "nationality_en" => "Ni-Vanuatu", "nationality_ar" => "فانواتي", "order" => 189],
            ["en_name" => "Vatican City", "ar_name" => "مدينة الفاتيكان", "country_code" => "VA", "phone_code" => "379", "currency_code" => "EUR", "nationality_en" => "Vatican", "nationality_ar" => "فاتيكاني", "order" => 190],
            ["en_name" => "Venezuela", "ar_name" => "فنزويلا", "country_code" => "VE", "phone_code" => "58", "currency_code" => "VES", "nationality_en" => "Venezuelan", "nationality_ar" => "فنزويلي", "order" => 191],
            ["en_name" => "Vietnam", "ar_name" => "فيتنام", "country_code" => "VN", "phone_code" => "84", "currency_code" => "VND", "nationality_en" => "Vietnamese", "nationality_ar" => "فيتنامي", "order" => 192],
            ["en_name" => "Yemen", "ar_name" => "اليمن", "country_code" => "YE", "phone_code" => "967", "currency_code" => "YER", "nationality_en" => "Yemeni", "nationality_ar" => "يمني", "order" => 193],
            ["en_name" => "Zambia", "ar_name" => "زامبيا", "country_code" => "ZM", "phone_code" => "260", "currency_code" => "ZMW", "nationality_en" => "Zambian", "nationality_ar" => "زامبي", "order" => 194],
            ["en_name" => "Zimbabwe", "ar_name" => "زيمبابوي", "country_code" => "ZW", "phone_code" => "263", "currency_code" => "BWP", "nationality_en" => "Zimbabwean", "nationality_ar" => "زيمبابوي", "order" => 195],
        ];

        foreach ($countries as $country) {
            Country::updateOrCreate(
                ['country_code' => $country['country_code']],
                array_merge($country, ['is_public' => true])
            );
        }
    }
}
